
const productos = [
    {
        id: 1,
        title:"Heladera Bottom Mount Inox Whirlpool 588 Lts - WRE85AK",
        description: "Tecnología que regula la temperatura automáticamente y beneficia la conservación de los alimentos. Refrigerador arriba y freezer abajo, permite mejor aprovechamiento interno, sus alimentos y bebidas siempre al alcance de las manos. Enfría rápidamente bebidas o postres y te avisa cuando están listos. Con 3 modos distintos: turbo 10, latas y espumantes.",
        stock: 10,
        type: "Heladeras",
        imageProduct: {
            firstImage: "heladera1.webp"
        },
        price: 966000,
    },
    {
        id: 2,
        title: "Heladera Bottom Mount Inox Whirlpool Blanca 588 Lts - WRE85AK",
        description: "Enfría rápidamente bebidas o postres y te avisa cuando están listos. Con 3 modos distintos: turbo 10, latas y espumantes. Refrigerador arriba y freezer abajo, permite mejor aprovechamiento interno, sus alimentos y bebidas siempre al alcance de las manos. Tecnología que regula la temperatura automáticamente y beneficia la conservación de los alimentos. Accedé rápido a las funciones: Turbo ice , turbo zone, fiesta, vacaciones y compras.",
        stock: 8,
        type: "Heladeras",
        imageProduct: {
            firstImage:" heladera2.webp",
        },
        price: 900000, 
    },
    {
        id: 3,
        title: "Heladera Whirlpool No Frost Xpert Inverter 500 Lts",
        description: "Nivel superior de tecnología y eficiencia que permite mayor ahorro de energía, brindándole al producto mejor rendimiento y durabilidad. Los compresores cuentan con tecnología que se ajusta a la demanda según lo requiera el refrigerador (velocidad variable), el resultado es una considerable reducción del consumo energético respecto a los compresores convencionales. Estantes y bandejas completamente flexibles para adaptar el espacio de guardado a las diferentes necesidades. ",
        stock: 3,
        type: "Heladeras",
        imageProduct: {
            firstImage:"heladera3.webp",
        },
        price: 812000, 
    },
    {
        id: 4,
        title: "Heladera Whirlpool No Frost Xpert Inverter de 462 Lts",
        description: "Nivel superior de tecnología y eficiencia que permite mayor ahorro de energía, brindándole al producto mejor rendimiento y durabilidad. Los compresores cuentan con tecnología que se ajusta a la demanda según lo requiera el refrigerador (velocidad variable), el resultado es una considerable reducción del consumo energético respecto a los compresores convencionales.Función exclusiva para acelerar la fabricación de hielo en ocasiones especiales. Permite ahorrar hasta 30 minutos. Una vez que el hielo está listo se enciende el panel, eso significa que el hielo ya está listo para ser extraído.",
        stock: 6,
        type: "Heladeras",
        imageProduct: {
            firstImage:"heladera4.webp",
        },
        price: 778000, 
    },
    {
        id: 5,
        title: "Heladera Whirlpool French Door Bottom Mount 554 Lts",
        description: "Nivel superior de tecnología y eficiencia que permite mayor ahorro de energía, brindándole al producto mejor rendimiento y durabilidad*. Los compresores cuentan con tecnología que se ajusta a la demanda según lo requiera el refrigerador (velocidad variable), el resultado es una considerable reducción del consumo energético respecto a los compresores convencionales. La tecnología Cooling Control mantiene una temperatura homogénea en la heladera al contar con múltiples salidas de aire en su interior. Los alimentos son bien conservados en cualquier ubicación.",
        stock: 9,
        type: "Heladeras",
        imageProduct: {
            firstImage:"heladera5.webp",
        },
        price: 1107299, 
    },
    {
         id: 6,
        title: "Heladera Whirlpool No Frost Xpert Inverter 443 Lts",
        description: "Nivel superior de tecnología y eficiencia que permite mayor ahorro de energía, brindándole al producto mejor rendimiento y durabilidad. Los compresores cuentan con tecnología que se ajusta a la demanda según lo requiera el refrigerador (velocidad variable), el resultado es una considerable reducción del consumo energético respecto a los compresores convencionales. ",
        stock: 3,
        type: "Heladeras",
        imageProduct: {
            firstImage:"heladera6.webp",
        },
        price: 826599, 
    },
    {
        id: 7,
        title: "Heladera Whirlpool No Frost Xpert Inverter de 462 Lts WRM56D2",
        description: "Esta línea de heladeras no frost con freezer abajo es elegante por fuera y gigante por dentro. Además cuenta con varias funciones que harán tu día a día mucho más sencillo.Posee capacidad de Side By Side pero sin ninguna division interior, lo que permite el maximo aprovechamiento del espacio tanto en el refigerador como en el freezer. Refrigerador arriba y freezer abajo, permite mejor aprovechamiento interno, sus alimentos y bebidas siempre al alcance de las manos.",
        stock: 1,
        type: "Heladeras",
        imageProduct: {
            firstImage:"heladera7.webp",
        },
        price: 73669, 
    },
    {
        id: 8,
        title: "Heladera Whirlpool No Frost Xpert Inverter 443 Lts WRE57D2",
        description: "La Whirlpool Big Foot es una heladera No Frost con panel touch, tiene una capacidad de 573 Litros y cuenta con un diseño innovador. Su línea moderna le aporta elegancia y tecnología a tu cocina. Posee funciones inteligentes y cuenta con diversos compartimientos que la hacen única y completa. La tecnología Evox le brinda a la puerta de tu heladera una película anti-huellas y resistente a la oxidación. Los modelos con tecnología Evox cuentan con 3 años de garantía anticorrosión y oxidación en la puerta.",
        stock: 7,
        type: "Heladeras",
        imageProduct: {
            firstImage:"heladera8.webp",
        },
        price: 785199, 
    },
    {
        id: 9,
        title: "Heladera Whirlpool No Frost Complete 573 Lts WRE80D2",
        description: "Heladera de Alta Capacidad con estilo Side by Side en la parte superior y Freezers ubicado en la parte inferior permitiendo tener mayor comodidad en el uso diario. Tecnología que brinda un mayor ahorro de energía y mantiene las temperaturas estables ayudando a la preservación de alimentos. Tecnología que regula la temperatura automáticamente y beneficia la conservación de los Alimentos.",
        stock: 10,
        type: "Heladeras",
        imageProduct: {
            firstImage:"heladera9.webp",
        },
        price: 803200, 
    },
    {
        id: 10,
        title: "Heladera Whirlpool No Frost 573 Lts WRE80K2",
        description: "Refrigera o congela tus alimentos mediante el reparto homogéneo de aire frío , sin necesidad de descongelar. Estantes removibles para brindar mayor comodidad y aprovechamiento del interior del Refrigerador. División especial para enfriar tus productos más rápido sin congelar. Control interno que permite ajustar la temperatura según las necesidades.",
        stock: 12,
        type: "Heladeras",
        imageProduct: {
            firstImage:"heladera10.png",
        },
        price: 920500, 
    },
    {
        id: 11,
        title: "Heladera Whirlpool No Frost 374 Lts Blanca WRM44HB",
        description: "Estantes removibles para brindar mayor comodidad y aprovechamiento del interior del Refrigerador. División especial para enfriar tus productos más rápido sin congelar. Control interno que permite ajustar la temperatura según las necesidades. Diseño diferenciado con manija emportrada. Refrigera o congela tus alimentos mediante el reparto homogéneo de aire frío , sin necesidad de descongelar .",
        stock: 2,
        type: "Heladeras",
        imageProduct: {
            firstImage:"heladera11.webp",
        },
        price: 960230, 
    },
    {
        id: 12,
        title: "Heladera Whirlpool No frost French Door 541Lts WRO80K2",
        description: "Las nuevas heladeras Whirlpool son No Frost y poseen una capacidad de 374 litros. Su tamaño es ideal para brindarte la comodidad que necesitas y la flexibilidad para que puedas adaptarla como desees. Su control externo de Temperatura te permite regular los 4 niveles de temperatura mas función Turbo sin abrir la puerta. Mové tus bebidas del refrigerador al freezer, para conseguir la temperatura ideal. Tus latas a mano, sin tomar espacio adicional de tu heladera.",
        stock: 3,
        type: "Heladeras",
        imageProduct: {
            firstImage:"heladera12.webp",
        },
        price: 900000, 
    },
    {
        id: 13,
        title: "Lavarropas Whirlpool Carga Superior 11KG Gris Oscuro WW11BT",
        description: "Deja la ropa en remojo, justo antes del último centrifugado, evitando que la ropa permanezca centrifugada en el interiordel tambor y se arrugue. En solo 30 minutos realiza un lavado a media carga para refrescar las prendas sin manchas. Añade un enjuague adicional al programa elegido.Seleccionando esta función se añade un aclarado / enjuague al programa elegido.El Super Enjuague es recomendado para personas alérgicas a los detergentes.",
        stock: 10,
        type: "Lavarropas",
        imageProduct: {
            firstImage:"lavarropas1.webp",
        },
        price: 300799, 
    },
    {
        id: 14,
        title: "Lavarropas Whirlpool Carga Superior 6 KG 1200 RPM WCS60ZB",
        description: "Sensores inteligentes detectan el nivel de carga para optimizar el ciclo minimizando el uso de recursos. Ahorra hasta 40% de agua y de energía, comparando lavados de carga mínima y máxima en un mismo ciclo. Ahorro superior, mejor rendimiento y durabilidad. Prendas como recién lavadas por hasta 6 horas de concluido el ciclo.",
        stock: 7,
        type: "Lavarropas",
        imageProduct: {
            firstImage:"lavarropas2.webp",
        },
        price: 301699,
    },
    {
        id: 15,
        title: "Lavarropas Whirlpool Carga Superior 11 KG Blanco WW11BL",
        description: "Tecnología con doble canasto que permite lavar simultáneamente prendas de distinto tipo. Ciclo de lavado pensado y desarrollado especialmente por Whirlpool que previene la aparición de pelusas en las prendas delicadas. Remueve más de 40 tipos de manchas, desde las más comunes hasta las más difíciles.",
        stock: 2,
        type: "Lavarropas",
        imageProduct: {
            firstImage:"lavarropas3.webp",
        },
        price: 278399,
    },
    {
        id: 16,
        title: "Lavarropas Whirlpool Carga Superior 7,5 KG 750 RPM Blanco WWH07ABK",
        description: "Sensores inteligentes detectan el nivel de carga para optimizar el ciclo minimizando el uso de recursos. Ahorra hasta 40% de agua y de energía, comparando lavados de carga mínima y máxima en un mismo ciclo. Prendas como recién lavadas por hasta 6 horas de concluido el ciclo. Inhibe la proliferación de las principales fuentes de mal olor dentro del producto hasta 6 horas después de finalizar el lavado según estudios realizados en laboratorio Innovhub - SSI - Milán, Italia.",
        stock: 1,
        type: "Lavarropas",
        imageProduct: {
            firstImage:"lavarropas4.webp",
        },
        price: 274299,
    },
    {
        id: 17,
        title: "Lavarropas Whirlpool Xpert Dual Wash 10 KG WWH10AT",
        description: "Ahorro superior, mejor rendimiento y durabilidad. Prendas como recién lavadas por hasta 6 horas de concluido el ciclo. STEAM REFRESH / REFRESCAR CON VAPOR ¡Potenciá tu lavado con vapor! ¡Refresca tu ropa y reduce hasta un 40% las arrugas!",
        stock: 8,
        type: "Lavarropas",
        imageProduct: {
            firstImage:"lavarropas5.png",
        },
        price: 335599,
    },
    {
        id: 18,
        title: "Lavarropas Whirlpool 9kg - 1400rpm Blanco Inverter WNQ90AB",
        description: "Sensores inteligentes detectan el nivel de carga para optimizar el ciclo minimizando el uso de recursos. Ahorra hasta 40% de agua y de energía, comparando lavados de carga mínima y máxima en un mismo ciclo. Ahorro superior, mejor rendimiento y durabilidad. Prendas como recién lavadas por hasta 6 horas de concluido el ciclo.",
        stock: 4,
        type: "Lavarropas",
        imageProduct: {
            firstImage:"lavarropas6.webp",
        },
        price: 369999,
    },
    {
        id: 19,
        title: "Lavarropas Whirlpool 7kg - 1200rpm Blanco Inverter WNQ70AB",
        description: "Remueve hasta 42 de las manchas más difíciles con agua fría, como desodorante y café con leche. Gracias a su configuración SmartAction (impeller, filtro, lifter) y este ciclo pensado especialmente para remover manchas difíciles, los resultados de lavado serán óptimos. Mejor remoción de pelos de mascotas! Remueve hasta un 80% más de pelos. Lavado con enjuague largo y doble para mayor filtraje de pelos.",
        stock: 2,
        type: "Lavarropas",
        imageProduct: {
            firstImage:"lavarropas7.png",
        },
        price: 369999,
    },
    {
        id: 20,
        title: "Lavarropas Whirlpool 8kg - 1200rpm Blanco Inverter WNQ80AB",
        description: "El ciclo Quita Manchas Pro alterna las condiciones ideales de temperatura y agitación para un máximo rendimiento de lavado, eliminando más de 40 tipos de manchas como grasa, desodorante y marcadores de colores, sin dañar las ropas. Ciclo de lavado especial que evita la formación de pelotitas en la ropa durante el proceso de lavado, manteniéndolas como nuevas por más tiempo. La gran capacidad de este lavarropas y su ergonomía permiten ingresar en la máquina edredones de hasta el tamaño de un queen size. Es un lavado pensado especialmente para cargas voluminosas.",
        stock: 9,
        type: "Lavarropas",
        imageProduct: {
            firstImage:"lavarropas8.png",
        },
        price: 301789,
    },
    {
        id: 21,
        title: "Lavarropas Whirlpool Carga Frontal 6 KG 800 RPM WNQ06AB",
        description: "Remueve hasta 42 de las manchas más difíciles con agua fría, como desodorante y café con leche. Gracias a su configuración SmartAction (impeller, filtro, lifter) y este ciclo pensado especialmente para remover manchas difíciles, los resultados de lavado serán óptimos. Mejor remoción de pelos de mascotas! Remueve hasta un 80% más de pelos. Lavado con enjuague largo y doble para mayor filtraje de pelos. Con el diseño innovador del panel de control en la tapa se obtiene una gran experiencia de uso al evitar que la misma quede expuesta a ropa húmeda. Este diseño permite una fácil limpieza y cuenta con un vidrio templado altamente resistente (máxima resistencia de la tapa hasta 80kg).",
        stock: 6,
        type: "Lavarropas",
        imageProduct: {
            firstImage:"lavarropas9.webp",
        },
        price: 289436,
    },
    {
        id: 22,
        title: "Lavarropas Whirlpool Carga Frontal Xpert Inverter 9 KG 1200 RPM WLF91AB",
        description: "Ahorro superior, mejor rendimiento y durabilidad. Motor inverter comparado con motor convencional en base a análisis y testeos sobre modelos matemáticos hechos por Whirlpool. Prendas como recién lavadas por hasta 6 horas de concluido el ciclo. Inhibe la proliferación de las principales fuentes de mal olor dentro del producto hasta 6 horas después de finalizar el lavado según estudios realizados en laboratorio Innovhub - SSI - Milán, Italia. ¡Refresca tu ropa y reduce hasta un 40% las arrugas! Basado en un testeo interno de Whirlpool de percepción humana de reducción de arrugas con prendas de algodón con una carga de 2 kg con uso y sin uso del ciclo.",
        stock: 3,
        type: "Lavarropas",
        imageProduct: {
            firstImage:"lavarropas10.webp",
        },
        price: 320980,
    },
    {
        id: 23,
        title: "Lavarropas Whirlpool Carga Frontal Xpert Inverter 7,5 KG 1000 RPM WLF75AB",
        description: "¡Potenciá tu lavado con vapor! Testeo interno de Whirlpool basado parcialmente en la norma IEC 60456:2010 sobre tres lavados usando el ciclo DIARIO con y sin vapor, con carga reducida de 4 kg para manchas de chocolate, vino tinto, carbón, sangre, grasa. Mejora hasta un 18% la remoción de manchas. ¡Refresca tu ropa y reduce hasta un 40% las arrugas! Basado en un testeo interno de Whirlpool de percepción humana de reducción de arrugas con prendas de algodón con una carga de 2 kg con uso y sin uso del ciclo.",
        stock: 7,
        type: "Lavarropas",
        imageProduct: {
            firstImage:"lavarropas11.webp",
        },
        price: 315670,
    },
    {
        id: 24,
        title: "Lavarropas Whirlpool Carga Frontal 7 KG 1000 RPM WNQ07AB",
        description: "Ahorro superior,mejor rendimiento y durabilidad. Suaves movimientos de tambor diseñados especialmente para el cuidado de tus prendas. Conserva los colores de las prendas con un lavado a baja temperatura. Ciclo para limpiar rápidamente las prendas con bajo nivel de suciedad en sólo 30 minutos, ahorrando tiempo y energía.(Debido a la duración del programa en comparación con ciclos de mayor duración del mismo producto).",
        stock: 3,
        type: "Lavarropas",
        imageProduct: {
            firstImage:"lavarropas12.webp",
        },
        price: 300925,
    },
    {
        id: 25,
        title: "Cocina Whirlpool Multigas 56 CM Blanca WFB57DW",
        description: "COCINA 51 CM COLOR BLANCA CAJON PARRILLA AUTOLIMPIANTE ESPEJADA 4 HORNALLAS CON VALVULA DE SEGURIDAD EN CADA UNA MANIJA CROMADA CHATA/REJILLA ENTERA.QUEMADORES ENLOZADOS. MULTIGAS",
        stock: 10,
        type: "Cocina",
        imageProduct: {
            firstImage:"cocina1.webp",
        },
        price: 226399,
    },
    {
        id: 26,
        title: "Cocina Whirlpool Multigas 58 CM Inox WFX57DI",
        description: "COCINA 58 CM COLOR BLANCA CAJON PARRILLA AUTOLIMPIANTE VIRIO VISOR 4 HORNALLAS CON VALVULA DE SEGURIDAD EN CADA UNA MANIJA RED PINTADA.QUEMADORES ENLOZADOS. MULTIGAS",
        stock: 8,
        type: "Cocina",
        imageProduct: {
            firstImage:"cocina2.webp",
        },
        price: 262999,
    },
    {
        id: 27,
        title: "Cocina Whirlpool Multigas 56 CM Inox WFX57DW",
        description: "Gabinete negro con plancha inoxidable. Horno autolimpiante con puerta espejada. Manija cromada. Quemadores de alta eficiencia. Cajon parrilla c/puerta abatible. Rejilla enteriza de alambre de acero. Ancho 51cm. Multigas",
        stock: 4,
        type: "Cocina",
        imageProduct: {
            firstImage:"cocina3.webp",
        },
        price: 245899,
    },
    {
        id: 28,
        title: "Cocina Whirlpool Multigas 57 CM Blanca WFB57DI",
        description: "Cocina 57cm color BLANCA plancha blanca 4 hornallas parrila Autolimp. espejada Manija cuadrada cromada quemad.alta eficiencia luz encendido pirometro doble vidrio rejilla dividida fundic ion con timer multigas valvula de seguridad en cada hornalla. Multigas. CON ENCENDIDO ELECTRICO.",
        stock: 6,
        type: "Cocina",
        imageProduct: {
            firstImage:"cocina4.webp",
        },
        price: 299999,
    },
    {
        id: 29,
        title: "Cocina Whirlpool Multigas 60 CM WF160XB",
        description: "Color negro. Horno autolimpiante. Puerta desmontable de cristal templado decorado, c/ visor. Cajon parrilla autolimpiante c/ puerta volcable. 4 Quemadores de alta potencia c/ tapas enlozadas.Valvula de seguridad en hornallas y horno. Multigas.",
        stock: 5,
        type: "Cocina",
        imageProduct: {
            firstImage:"cocina5.webp",
        },
        price: 310200,
    },
    {
        id: 30,
        title: "Cocina Whirlpool Multigas 60 cm Inox WF560XT",
        description: "COCINA 51 CM COLOR NEGRA 4 HORNALLAS CON VALVULA DE SEGURIDAD EN CADA UNA MANIJA PINTADA/REJILLA ENTERA. MULTIGAS",
        stock: 8,
        type: "Cocina",
        imageProduct: {
            firstImage:"cocina6.webp",
        },
        price: 345000,
    },
    {
        id: 31,
        title: "Cocina Whirlpool Multigas 76 CM Inox WF976XC",
        description: "Plancha de acero inox. Horno QuickClean (antiadherente) con luz y puerta con doble vidrio templado. 4 Hornallas de 3 diferentes potencias. Encendido electronico y valvula de seguridad en hornallas y horno. Parrilla-grill independiente, extraible con 3 posiciones",
        stock: 9,
        type: "Cocina",
        imageProduct: {
            firstImage:"cocina7.webp",
        },
        price: 286000,
    },
    {
        id: 32,
        title: "Cocina Whirlpool Multigas 60 CM Inox WF360XG",
        description: "COCINA 51 CM COLOR BLANCA 4 HORNALLAS CON VALVULA DE SEGURIDAD EN CADA UNA MANIJA PINTADA/REJILLA ENTERA. MULTIGAS",
        stock: 6,
        type: "Cocina",
        imageProduct: {
            firstImage:"cocina8.webp",
        },
        price: 315000,
    },
    {
        id: 33,
        title: "Cocina Whirlpool Multigas 76 cm Inox WF876XG",
        description: "Totalmente enlozada. Puerta de horno c/visor y bisagra desmontable. Quemadores de alto rendimiento. Doble aislacion termica. Cajon parrilla independiente. Reja superior enteriza enlozada. Valvula de seguridad y termocupla en hornallas y horno. Para GE",
        stock: 2,
        type: "Cocina",
        imageProduct: {
            firstImage:"cocina9.webp",
        },
        price: 203000,
    },
]

export default productos;